### ISSUE TITLE
List of groups does not update when a new group is created

### ISSUE THREAD

**Issue by brendanzab** [zendesk/notification_app#12]
Steps to reproduce:
1. Start the notification app with zat
2. Open up notifications panel and type the first few letters of an existing group in the group box - a drop down list should appear with the full name
3. Create a new group via `settings>people`
4. Open up notifications panel and type the first few letters of the new group's name in the group box - no matching group name should appear

This probably because we only look up the group list one, [during app initialization](https://github.com/zendesk/notification_app/blob/8cde897718d9006bf999e9dd1e2dc69c6e62ad8c/app.js#L50-L63).

**Comment by ocke** [comment]
very minor bug, that is a problem for a lot of apps. Also a problem in lotus itself.
